name: windows-arm64-binary-test

on:
  workflow_call:
    inputs:
      build_name:
        required: true
        type: string
      PACKAGE_TYPE:
        required: true
        type: string
      DESIRED_CUDA:
        required: true
        type: string
      GPU_ARCH_TYPE:
        required: true
        type: string
      DESIRED_PYTHON:
        required: false
        type: string
      LIBTORCH_CONFIG:
        required: false
        type: string
      LIBTORCH_VARIANT:
        required: false
        type: string
      runs_on:
        required: false
        type: string
        default: windows-11-arm64-preview
      timeout-minutes:
        required: false
        type: number
        default: 360
    secrets:
      github-token:
        required: true

permissions:
  id-token: write

jobs:
  test:
    runs-on: ${{ inputs.runs_on }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    env:
      PYTORCH_ROOT: ${{ github.workspace }}
      PACKAGE_TYPE: ${{ inputs.PACKAGE_TYPE }}
      # TODO: This is a legacy variable that we eventually want to get rid of in
      #       favor of GPU_ARCH_VERSION
      DESIRED_CUDA: ${{ inputs.DESIRED_CUDA }}
      GPU_ARCH_TYPE: ${{ inputs.GPU_ARCH_TYPE }}
      SKIP_ALL_TESTS: 1
      DESIRED_PYTHON: ${{ inputs.DESIRED_PYTHON }}
      LIBTORCH_CONFIG: ${{ inputs.LIBTORCH_CONFIG }}
      LIBTORCH_VARIANT: ${{ inputs.LIBTORCH_VARIANT }}
    steps:
      - name: Populate binary env
        shell: cmd
        run: |
          echo BINARY_ENV_FILE=%RUNNER_TEMP%/env>> %GITHUB_ENV%
          echo PYTORCH_FINAL_PACKAGE_DIR=%RUNNER_TEMP%/artifacts>> %GITHUB_ENV%
          echo WIN_PACKAGE_WORK_DIR=%RUNNER_TEMP%>> %GITHUB_ENV%
      - name: Enable long paths
        shell: cmd
        run: |
          git config --system --get core.longpaths || echo "core.longpaths is not set, setting it now"
          git config --system core.longpaths true
      - name: Git checkout PyTorch
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Bootstrap APL
        shell: cmd
        run: |
          ".ci/pytorch/windows/arm64/bootstrap_apl.bat"
      - name: Bootstrap Python
        shell: cmd
        run: |
          ".ci/pytorch/windows/arm64/bootstrap_python.bat"
      - name: Bootstrap Rust
        shell: cmd
        run: |
          ".ci/pytorch/windows/arm64/bootstrap_rust.bat"
      - uses: actions/download-artifact@v4.1.7
        name: Download Build Artifacts
        with:
          name: ${{ inputs.build_name }}
          path: "${{ env.PYTORCH_FINAL_PACKAGE_DIR }}"
      - name: Populate binary env
        shell: bash
        run: |
          "${PYTORCH_ROOT}/.ci/pytorch/binary_populate_env.sh"
      - name: Test PyTorch binary
        shell: bash
        run: |
          "${PYTORCH_ROOT}/.ci/pytorch/binary_windows_test.sh"
